name: boardgame_io
version: 0.0.1
description: >-
  This package includes Dart classes for interacting with
  the backend of the boardgame.io NodeJs service. You will
  still need to create your game description and game
  server in one of the languages supported by boardgame.io
  but you can create your front-end in Flutter using this
  package as a bridge.
repository: http://github.com/flarbear/boardgame_io

environment:
  sdk: '>=2.9.0 <3.0.0'

dependencies:
  universal_io: ^1.0.2
  http: ^0.12.2
  socket_io_client: ^1.0.0-nullsafety.0
  logging: ^1.0.0-nullsafety.0
