name: tic_tac_toe
description: A sample project for dart_boardgame_io.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.9.0-0 <3.0.0"

dependencies:
  args: ^2.0.0-nullsafety.0
  universal_io: ^1.0.2
  boardgame_io:
    path: ../..
